// Generated by gencpp from file bno055/bno055_info.msg
// DO NOT EDIT!


#ifndef BNO055_MESSAGE_BNO055_INFO_H
#define BNO055_MESSAGE_BNO055_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bno055
{
template <class ContainerAllocator>
struct bno055_info_
{
  typedef bno055_info_<ContainerAllocator> Type;

  bno055_info_()
    : header()
    , tempC(0.0)
    , accelCalibration(0)
    , gyroCalibration(0)
    , magnoCalibration(0)
    , sysCalibration(0)  {
    }
  bno055_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tempC(0.0)
    , accelCalibration(0)
    , gyroCalibration(0)
    , magnoCalibration(0)
    , sysCalibration(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _tempC_type;
  _tempC_type tempC;

   typedef uint8_t _accelCalibration_type;
  _accelCalibration_type accelCalibration;

   typedef uint8_t _gyroCalibration_type;
  _gyroCalibration_type gyroCalibration;

   typedef uint8_t _magnoCalibration_type;
  _magnoCalibration_type magnoCalibration;

   typedef uint8_t _sysCalibration_type;
  _sysCalibration_type sysCalibration;





  typedef boost::shared_ptr< ::bno055::bno055_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bno055::bno055_info_<ContainerAllocator> const> ConstPtr;

}; // struct bno055_info_

typedef ::bno055::bno055_info_<std::allocator<void> > bno055_info;

typedef boost::shared_ptr< ::bno055::bno055_info > bno055_infoPtr;
typedef boost::shared_ptr< ::bno055::bno055_info const> bno055_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bno055::bno055_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bno055::bno055_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bno055::bno055_info_<ContainerAllocator1> & lhs, const ::bno055::bno055_info_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tempC == rhs.tempC &&
    lhs.accelCalibration == rhs.accelCalibration &&
    lhs.gyroCalibration == rhs.gyroCalibration &&
    lhs.magnoCalibration == rhs.magnoCalibration &&
    lhs.sysCalibration == rhs.sysCalibration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bno055::bno055_info_<ContainerAllocator1> & lhs, const ::bno055::bno055_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bno055

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bno055::bno055_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bno055::bno055_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bno055::bno055_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bno055::bno055_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bno055::bno055_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bno055::bno055_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bno055::bno055_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1818d2af59dc79e8470c9bf920f48a8";
  }

  static const char* value(const ::bno055::bno055_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1818d2af59dc79eULL;
  static const uint64_t static_value2 = 0x8470c9bf920f48a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::bno055::bno055_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bno055/bno055_info";
  }

  static const char* value(const ::bno055::bno055_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bno055::bno055_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 tempC\n"
"uint8 accelCalibration\n"
"uint8 gyroCalibration\n"
"uint8 magnoCalibration\n"
"uint8 sysCalibration\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::bno055::bno055_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bno055::bno055_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tempC);
      stream.next(m.accelCalibration);
      stream.next(m.gyroCalibration);
      stream.next(m.magnoCalibration);
      stream.next(m.sysCalibration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bno055_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bno055::bno055_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bno055::bno055_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tempC: ";
    Printer<double>::stream(s, indent + "  ", v.tempC);
    s << indent << "accelCalibration: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accelCalibration);
    s << indent << "gyroCalibration: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gyroCalibration);
    s << indent << "magnoCalibration: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.magnoCalibration);
    s << indent << "sysCalibration: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysCalibration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BNO055_MESSAGE_BNO055_INFO_H
